version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/doc/node-bulletin-board/bulletin-board-app
hooks:
  BeforeInstall:
    - location: scripts/crf2.sh
      timeout: 300
      runas: root
